### ISSUE TITLE
How to build the plugin?

### ISSUE THREAD

**Issue by eugenschindler** [patrick-winter-knime/knime-hdf5#1]
Hi, I was trying to use your plugin, but did not succeed adding it to Knime. Do I need to build it? If yes, how? If no, what do I do to install the plugin in Knime? I tried just adding the org.knime.hdf5 folder to plugins, but then Knime complains that it cannot find the HDF5ReaderNodeFactory and the HDF5WriterNodeFactory.
I was trying to build, but ant says there is no build.xml, although I can see a build.properties.
It would be really helpful to know how to use your plugin. Thanks a lot in advance for any hints!

**Comment by patrick-winter-kn** [comment]
We do now provide an update site. The installation instructions can be found in the [README](https://github.com/patrick-winter-knime/knime-hdf5/blob/master/README.md).
